workspace:
  base: /code
  path: ""

steps:
  build:
    image: quay.kawa.tf/tqdv/smapi-mod:3.18.4
    commands:
      - cp UIInfoSuite2/UIInfoSuite2-woodpecker.csproj.local UIInfoSuite2/UIInfoSuite2.csproj.local
      - dotnet build -c Release
    when:
      - event: [push, tag, manual]
  publish:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: UIInfoSuite2/bin/Release/*/UIInfoSuite2*.zip
      title: ${CI_COMMIT_BRANCH}
      prerelease: true
    when:
      - event: [push, tag, manual]